// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Delegate is an autogenerated mock type for the Delegate type
type Delegate struct {
	mock.Mock
}

// Handle provides a mock function with given fields: action, fromState, toState, args
func (_m *Delegate) Handle(action string, fromState string, toState string, args []interface{}) error {
	ret := _m.Called(action, fromState, toState, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, []interface{}) error); ok {
		r0 = rf(action, fromState, toState, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
