// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Delegate is an autogenerated mock type for the Delegate type
type Delegate struct {
	mock.Mock
}

// Handle provides a mock function with given fields: action, fromState, toState, args
func (_m *Delegate) Handle(action string, fromState string, toState string, args []interface{}) {
	_m.Called(action, fromState, toState, args)
}
