// Code generated by mockery v1.0.0
package mocks

import fsm "github.com/goph/fsm"
import mock "github.com/stretchr/testify/mock"

// StateMachineAwareDelegate is an autogenerated mock type for the StateMachineAwareDelegate type
type StateMachineAwareDelegate struct {
	mock.Mock
}

// SetStateMachine provides a mock function with given fields: sm
func (_m *StateMachineAwareDelegate) SetStateMachine(sm *fsm.StateMachine) {
	_m.Called(sm)
}
